---
apiVersion: v1
kind: Namespace
metadata:
  name: apt-cacher-ng
  labels:
    app.kubernetes.io/name: apt-cacher-ng
    app.kubernetes.io/component: apt-cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apt-cacher-ng-storage
  namespace: apt-cacher-ng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
  labels:
    app.kubernetes.io/name: apt-cacher-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apt-cacher-ng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apt-cacher-ng
    spec:
      containers:
        - name: apt-cacher-ng
          image: sameersbn/apt-cacher-ng:3.7.4-20220421
          ports:
            - containerPort: 3142
              name: http
          volumeMounts:
            - name: storage
              mountPath: /var/cache/apt-cacher-ng
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 3142
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 3142
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: apt-cacher-ng-storage

---
apiVersion: v1
kind: Service
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
  labels:
    app.kubernetes.io/name: apt-cacher-ng
spec:
  type: ClusterIP
  ports:
    - port: 3142
      targetPort: 3142
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: apt-cacher-ng
