apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-daemon-config
  namespace: arc-runners
data:
  daemon.json: |
    {
        "registry-mirrors": ["https://docker-mirror.ase.in.tum.de:8765"],
        "insecure-registries": ["docker-mirror.ase.in.tum.de:8765"]
    }
