apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-cache-pvc-1
  namespace: arc-runners
  labels:
    app: arc-runner
    runner-set: "1"
    cache-type: docker-layers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
